/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovagitxRouteImport } from './routes/novagitx'
import { Route as NovafinderRouteImport } from './routes/novafinder'
import { Route as LumiaRouteImport } from './routes/lumia'
import { Route as CirrusRouteImport } from './routes/cirrus'
import { Route as IndexRouteImport } from './routes/index'

const NovagitxRoute = NovagitxRouteImport.update({
  id: '/novagitx',
  path: '/novagitx',
  getParentRoute: () => rootRouteImport,
} as any)
const NovafinderRoute = NovafinderRouteImport.update({
  id: '/novafinder',
  path: '/novafinder',
  getParentRoute: () => rootRouteImport,
} as any)
const LumiaRoute = LumiaRouteImport.update({
  id: '/lumia',
  path: '/lumia',
  getParentRoute: () => rootRouteImport,
} as any)
const CirrusRoute = CirrusRouteImport.update({
  id: '/cirrus',
  path: '/cirrus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cirrus': typeof CirrusRoute
  '/lumia': typeof LumiaRoute
  '/novafinder': typeof NovafinderRoute
  '/novagitx': typeof NovagitxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cirrus': typeof CirrusRoute
  '/lumia': typeof LumiaRoute
  '/novafinder': typeof NovafinderRoute
  '/novagitx': typeof NovagitxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cirrus': typeof CirrusRoute
  '/lumia': typeof LumiaRoute
  '/novafinder': typeof NovafinderRoute
  '/novagitx': typeof NovagitxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cirrus' | '/lumia' | '/novafinder' | '/novagitx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cirrus' | '/lumia' | '/novafinder' | '/novagitx'
  id: '__root__' | '/' | '/cirrus' | '/lumia' | '/novafinder' | '/novagitx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CirrusRoute: typeof CirrusRoute
  LumiaRoute: typeof LumiaRoute
  NovafinderRoute: typeof NovafinderRoute
  NovagitxRoute: typeof NovagitxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/novagitx': {
      id: '/novagitx'
      path: '/novagitx'
      fullPath: '/novagitx'
      preLoaderRoute: typeof NovagitxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novafinder': {
      id: '/novafinder'
      path: '/novafinder'
      fullPath: '/novafinder'
      preLoaderRoute: typeof NovafinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumia': {
      id: '/lumia'
      path: '/lumia'
      fullPath: '/lumia'
      preLoaderRoute: typeof LumiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cirrus': {
      id: '/cirrus'
      path: '/cirrus'
      fullPath: '/cirrus'
      preLoaderRoute: typeof CirrusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CirrusRoute: CirrusRoute,
  LumiaRoute: LumiaRoute,
  NovafinderRoute: NovafinderRoute,
  NovagitxRoute: NovagitxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
